# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AstronautLister' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AstronautLister
  pod 'SDWebImage'

  target 'AstronautListerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
